export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const DELETE_CURRENT_USER = "DELETE_CURRENT_USER";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_TOURS = "GET_TOURS";
export const TOURS_LOADING = "TOURS_LOADING";
